name: pipeline

on:
  push:
    branches:
    - dev
    - main
  
  pull_request:
    branches:
    - dev
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout 
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws_region: us-east-1
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Deploy code to s3
      run: |
        branch=${GITHUB_REF#refs/heads/}
        case ${branch} in
          dev) aws s3 sync ./ s3://caniprjs/apple-store/dev --exact-timestamps --delete;
          main) aws s3 sync ./ s3://caniprjs/apple-store/main --exact-timestamps --delete;
        esac
        
